name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - name: Generate Waka Stats
        uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SYMBOL_VERSION: 1
          DEBUG_LOGGING: "False"
          SHOW_UPDATED_DATE: "False"

        # uses: athul/waka-readme@master #PLEASE USE MASTER BRANCH
        # with:
        #   WAKATIME_API_KEY: ${{ secrets.WAKA_API_KEY }}
        #   GH_TOKEN: ${{ secrets.GH_TOKEN }}
        #   SHOW_TIME: true
        #   SHOW_MASKED_TIME: true
        #   COMMITTER_NAME: "GitHub Actions"
        #   COMMITTER_EMAIL: "githubactions@github.com.br"
        #   AUTHOR_NAME: "GitHub Actions"
        #   AUTHOR_EMAIL: "githubactions@github.com.br"
